version: "3.9"

services:
  pinger:
    container_name:
      svc-pinger
    build:
      context: .
      dockerfile: pinger/Dockerfile
    image: pinger
    ports:
      - "8080:8080"
    networks:
      - db-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env

  check-1:
    image: alpine
    command: [ "sh", "-c", "while true; do sleep 3600; done" ]
    networks:
      - db-network

  check-2:
    image: alpine
    command: [ "sh", "-c", "while true; do sleep 3600; done" ]
    networks:
      - db-network

networks:
  db-network: