version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - containers-network
    env_file:
      - .env
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - REACT_APP_API_LOCATION=${REACT_APP_API_LOCATION}
      - REACT_APP_REFRESH_INTERVAL=${REACT_APP_REFRESH_INTERVAL}
    command: sh -c "envsubst '$$REACT_APP_API_LOCATION $$BACKEND_HOST $$BACKEND_PORT' < /etc/nginx/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  backend:
    container_name:
      ${BACKEND_HOST}
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: backend

    #TODO: delete ports
    ports:
      - "8083:8082"

    depends_on:
      db:
        condition: service_healthy
    networks:
      - containers-network
      - db-network
    env_file:
      - .env

  pinger:
    container_name:
      pinger
    build:
      context: .
      dockerfile: pinger/Dockerfile
    image: pinger
    depends_on:
      backend:
        condition: service_started
    networks:
      - containers-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
  check-1:
    image: alpine
    command: [ "sh", "-c", "while true; do sleep 3600; done" ]
    networks:
      - containers-network

  check-2:
    image: alpine
    command: [ "sh", "-c", "while true; do sleep 3600; done" ]
    networks:
      - containers-network

  db:
    image: postgres:16.6-alpine3.21
    restart: always
    container_name: db-postgres
    networks:
      - db-network
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - containers:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${DB}
      interval: 5s
      timeout: 3s
      retries: 5


volumes:
  containers:
networks:
  containers-network:
  db-network: