version: "3.9"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "9000:8080"
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - .:/docs

  asyncapi-ui:
    image: asyncapi/studio
    container_name: asyncapi-ui
    ports:
      - "9001:80"
    volumes:
      - .:/usr/share/nginx/html/docs